version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: smart-ac-api
    env_file:
      - apps/api/.env
    ports:
      - "3000:3000"
    restart: unless-stopped
    # Uncomment to run with local code mounted for quick iteration
    # volumes:
    #   - ./:/workspace

